[09-12-2021 02:35:14 AM: - INFO: 34:] - connect_database.py - Accessing cassandra connectivity...
[09-12-2021 02:35:15 AM: - INFO: 42:] - connect_database.py - Connecting cassandra db is done...
[09-12-2021 02:35:18 AM: - INFO: 53:] - connect_database.py - Accessing rows from cassandra db is done...
[09-12-2021 02:35:18 AM: - INFO: 57:] - connect_database.py - Data has been successfully saved to given folder.
